/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-page': HomePage;
    'about-page': AboutPage;
    'products-page': ProductsPage;
    'careers-page': CareersPage;
    'blog-posts': BlogPost;
    'contact-page': ContactPage;
    products: Product;
    'dashboard-home-page': DashboardHomePage;
    'product-details': ProductDetail;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'dashboard-home-page': DashboardHomePageSelect<false> | DashboardHomePageSelect<true>;
    'product-details': ProductDetailsSelect<false> | ProductDetailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  /**
   * Folder path in Cloudinary (e.g., products/2024)
   */
  cloudinaryFolder?: string | null;
  /**
   * Select transformations to apply. Note: Only one preset from each category (Size, Effect, etc.) will be applied.
   */
  transformationPreset?:
    | (
        | 'thumbnail'
        | 'card'
        | 'banner'
        | 'hero'
        | 'feature'
        | 'avatar'
        | 'profile-header'
        | 'og-image'
        | 'twitter-card'
        | 'instagram-square'
        | 'instagram-story'
        | 'square'
        | 'landscape-16-9'
        | 'landscape-4-3'
        | 'portrait-9-16'
        | 'blur'
        | 'grayscale'
        | 'sepia'
        | 'pixelate'
        | 'sharpen'
        | 'vignette'
        | 'auto-optimize'
        | 'high-quality'
        | 'balanced'
        | 'eco-mode'
        | 'progressive'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage the home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  title: string;
  locale: 'en' | 'ja';
  heroSlides?:
    | {
        type: 'zibot' | 'glide' | 'consultancy' | 'custom';
        title?: string | null;
        subtitle?: string | null;
        cursiveText?: string | null;
        image?: (number | null) | Media;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  videoSection: {
    enabled?: boolean | null;
    videoUrl: string;
    /**
     * Optional poster image for video
     */
    posterImage?: (number | null) | Media;
  };
  aboutSection: {
    foundation: {
      label?: string | null;
      title: string;
      description: string;
      ctaText?: string | null;
      ctaLink?: string | null;
    };
    purpose: {
      label?: string | null;
      title: string;
      description: string;
      image: number | Media;
    };
    vision: {
      label?: string | null;
      title: string;
      description: string;
      image: number | Media;
    };
    mission: {
      label?: string | null;
      title: string;
      description: string;
      image: number | Media;
      highlights?:
        | {
            title: string;
            subtitle: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  products?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        link: string;
        /**
         * Reverse layout (image on left)
         */
        reverse?: boolean | null;
        features?:
          | {
              title: string;
              subtitle: string;
              icon:
                | 'Clock'
                | 'DollarSign'
                | 'Leaf'
                | 'Shield'
                | 'Package'
                | 'CheckCircle'
                | 'UtensilsCrossed'
                | 'Hotel';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  customSolutions?:
    | {
        id: string;
        category: string;
        title: string;
        description: string;
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        features?:
          | {
              title: string;
              subtitle: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  metricsSection?: {
    title?: string | null;
    subtitle?: string | null;
    animatedStats?:
      | {
          value: number;
          label: string;
          icon: 'Package' | 'UtensilsCrossed' | 'Hotel' | 'MapPin' | 'Globe2' | 'CheckCircle';
          id?: string | null;
        }[]
      | null;
    staticStats?:
      | {
          value: string;
          label: string;
          icon: 'MapPin' | 'Globe2' | 'CheckCircle';
          id?: string | null;
        }[]
      | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        locale: 'en' | 'ja';
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the about page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  locale: 'en' | 'ja';
  heroSection: {
    title: string;
    subtitle: string;
    bannerImage?: (number | null) | Media;
  };
  foundedSection: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  peopleBannerSection: {
    title: string;
    description: string;
    bannerImage?: (number | null) | Media;
  };
  visionSection: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  leadershipSection: {
    title: string;
    subtitle: string;
    teamMembers?:
      | {
          name: string;
          role: string;
          imageUrl: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection: {
    title: string;
    description: string;
    bannerImage?: (number | null) | Media;
    buttons?:
      | {
          text: string;
          link: string;
          variant: 'primary' | 'outline';
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the products page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: number;
  title: string;
  locale: 'en' | 'ja';
  heroSection: {
    title: string;
    subtitle: string;
    bannerImage?: (number | null) | Media;
  };
  products?:
    | {
        /**
         * Unique identifier for anchor links (e.g., "zibot", "glide")
         */
        id: string;
        title: string;
        description: string;
        image?: (number | null) | Media;
        link: string;
        /**
         * Reverse layout (image on right)
         */
        reverse?: boolean | null;
        features?:
          | {
              title: string;
              subtitle: string;
              icon:
                | 'Clock'
                | 'DollarSign'
                | 'Leaf'
                | 'Shield'
                | 'Package'
                | 'CheckCircle'
                | 'UtensilsCrossed'
                | 'Hotel';
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  customSolutions?:
    | {
        /**
         * Unique identifier (e.g., "customized-robots", "iot-solutions")
         */
        id: string;
        category: string;
        title: string;
        description: string;
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        features?:
          | {
              title: string;
              subtitle: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  ctaSection: {
    text: string;
    link: string;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        locale: 'en' | 'ja';
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the Careers page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  title: string;
  heroSection: {
    title: string;
    subtitle: string;
    backgroundImage?: (number | null) | Media;
  };
  introSection: {
    description: string;
  };
  departmentsSection?: {
    departments?:
      | {
          title: string;
          description: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    ctaButtonText?: string | null;
  };
  missionSection: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  facilitiesSection: {
    title: string;
    description: string;
    backgroundImage?: (number | null) | Media;
  };
  benefitsSection: {
    title: string;
    description: string;
    benefits?:
      | {
          benefit: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  innovationSection: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  growthSection: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  peopleImageSection?: {
    image?: (number | null) | Media;
  };
  ctaSection: {
    title: string;
    description: string;
    buttonText?: string | null;
  };
  jobs?:
    | {
        title: string;
        location: string;
        /**
         * e.g., "November 20, 2025"
         */
        date: string;
        type: 'Full time' | 'Part time' | 'Contract' | 'Internship';
        salary?: string | null;
        skills?:
          | {
              skill: string;
              id?: string | null;
            }[]
          | null;
        description?: string | null;
        responsibilities?:
          | {
              responsibility: string;
              id?: string | null;
            }[]
          | null;
        requirements?:
          | {
              requirement: string;
              id?: string | null;
            }[]
          | null;
        qualifications?:
          | {
              qualification: string;
              id?: string | null;
            }[]
          | null;
        benefits?:
          | {
              benefit: string;
              id?: string | null;
            }[]
          | null;
        techStack?:
          | {
              tech: string;
              id?: string | null;
            }[]
          | null;
        imageKey?: ('product' | 'engineering' | 'innovation' | 'worldclass' | 'people') | null;
        /**
         * e.g., "December 20, 2025"
         */
        applyBefore?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage blog posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  category: 'business' | 'technology' | 'case-study' | 'careers' | 'sustainability';
  /**
   * Short description or excerpt for the blog post
   */
  description: string;
  featuredImage?: (number | null) | Media;
  publishedDate: string;
  /**
   * e.g., "5 min read"
   */
  readTime?: string | null;
  /**
   * Mark this post as featured (shown prominently on blog page)
   */
  featured?: boolean | null;
  /**
   * Full blog post content
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Number of views (auto-incremented)
   */
  views?: number | null;
  /**
   * Number of likes
   */
  likes?: number | null;
  /**
   * Select the author from registered users
   */
  author?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the Contact Us page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  heroSection: {
    title: string;
    description: string;
  };
  socialMedia?: {
    twitter?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
  };
  contactInfo: {
    email: string;
    phone: string;
    officeAddress: {
      en: string;
      ja: string;
    };
  };
  mapLocation: {
    /**
     * e.g., 35.157308228381325
     */
    latitude: number;
    /**
     * e.g., 136.96488391534322
     */
    longitude: number;
  };
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage products and services
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Product name (e.g., "ZiBot & Glide")
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Category badge (e.g., "Robotics", "Consultancy")
   */
  category: string;
  /**
   * Display title for the product
   */
  title: string;
  description: string;
  images?:
    | {
        image: number | Media;
        alt: string;
        /**
         * Optional label overlay (e.g., "ZiBot", "Glide")
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        /**
         * Emoji icon (e.g., "🤖", "🛴")
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  /**
   * Layout configuration for the product display
   */
  layout: 'image-right' | 'image-left' | 'image-grid';
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  locale: 'en' | 'ja';
  /**
   * Show/hide this product
   */
  isActive?: boolean | null;
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the Dashboard home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-home-page".
 */
export interface DashboardHomePage {
  id: number;
  title: string;
  heroSection: {
    /**
     * Text for the badge above the title
     */
    badgeText: string;
    title: string;
    description: string;
    primaryButtonText: string;
    primaryButtonLink?: string | null;
    secondaryButtonText: string;
    secondaryButtonLink?: string | null;
    /**
     * Text below the buttons (e.g., "Already have a Fainzy Business account?")
     */
    footerText?: string | null;
  };
  dashboardSection: {
    /**
     * Dashboard preview image
     */
    image: number | Media;
  };
  productsSection: {
    title: string;
    description: string;
    /**
     * Select products to display on the homepage
     */
    products?: (number | Product)[] | null;
  };
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage product detail pages with flexible section-based content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-details".
 */
export interface ProductDetail {
  id: number;
  /**
   * Product name (e.g., "ZiBot")
   */
  productName: string;
  /**
   * URL-friendly identifier (e.g., "zibot")
   */
  slug: string;
  /**
   * Add and reorder sections to build your product page
   */
  sections?:
    | {
        sectionType:
          | 'hero'
          | 'videoWithText'
          | 'largeFeatureCarousel'
          | 'cardCarousel'
          | 'robotComparison'
          | 'robotTopViewGrid'
          | 'videoWithStats'
          | 'benefitGrid'
          | 'pricing'
          | 'backgroundVideo'
          | 'specifications'
          | 'footerCTA';
        hero?: {
          /**
           * Background video for hero section
           */
          backgroundVideo?: (number | null) | Media;
          /**
           * Large hero title (e.g., "ZIBOT")
           */
          title?: string | null;
          /**
           * Subtitle/tagline below title
           */
          tagline?: string | null;
          /**
           * Primary call-to-action button text
           */
          primaryCTA?: string | null;
          stats?:
            | {
                /**
                 * Stat value (e.g., "50km")
                 */
                value: string;
                /**
                 * Stat label (e.g., "Range")
                 */
                label: string;
                id?: string | null;
              }[]
            | null;
        };
        videoWithText?: {
          /**
           * Video file
           */
          video?: (number | null) | Media;
          /**
           * Video poster image
           */
          poster?: (number | null) | Media;
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section description
           */
          description?: string | null;
          titlePosition?: ('above' | 'below' | 'overlay') | null;
          height?: ('small' | 'medium' | 'large') | null;
          /**
           * Optional overlay text
           */
          overlayText?: string | null;
          overlayPosition?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center') | null;
        };
        largeFeatureCarousel?: {
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section subtitle
           */
          subtitle?: string | null;
          features?:
            | {
                image?: (number | null) | Media;
                title?: string | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        cardCarousel?: {
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section subtitle
           */
          subtitle?: string | null;
          /**
           * Number of cards visible at once
           */
          cardsPerView?: number | null;
          navigationPosition?: ('top-left' | 'top-right' | 'bottom') | null;
          cards?:
            | {
                image?: (number | null) | Media;
                title?: string | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        robotComparison?: {
          /**
           * Robot comparison image
           */
          robotImage?: (number | null) | Media;
          specs?:
            | {
                /**
                 * Spec value (e.g., "125kg")
                 */
                value?: string | null;
                /**
                 * Spec label (e.g., "Max Load")
                 */
                label?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        robotTopViewGrid?: {
          /**
           * Robot top view image
           */
          robotImage?: (number | null) | Media;
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section subtitle
           */
          subtitle?: string | null;
          gridCols?: ('2' | '3' | '6') | null;
          gridItems?:
            | {
                image?: (number | null) | Media;
                title?: string | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          rightContentType?: ('none' | 'cta' | 'appButtons') | null;
          /**
           * Text for right content area
           */
          rightContentText?: string | null;
          /**
           * Button text for CTA
           */
          rightContentButtonText?: string | null;
        };
        videoWithStats?: {
          /**
           * Background video
           */
          video?: (number | null) | Media;
          /**
           * Video poster image
           */
          poster?: (number | null) | Media;
          /**
           * Section title
           */
          title?: string | null;
          stats?:
            | {
                value?: string | null;
                label?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * CTA button text
           */
          ctaText?: string | null;
          /**
           * CTA button link
           */
          ctaLink?: string | null;
        };
        benefitGrid?: {
          /**
           * Main section title
           */
          title?: string | null;
          sections?:
            | {
                /**
                 * Section heading (e.g., "For Store Owners")
                 */
                heading?: string | null;
                /**
                 * Section subheading
                 */
                subheading?: string | null;
                items?:
                  | {
                      image?: (number | null) | Media;
                      title?: string | null;
                      description?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
        };
        pricing?: {
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section description
           */
          description?: string | null;
          /**
           * Robot image for pricing section
           */
          robotImage?: (number | null) | Media;
          robotImageHeight?: ('small' | 'medium' | 'large') | null;
          pricingTiers?:
            | {
                /**
                 * Tier name (e.g., "Standard", "Premium")
                 */
                name?: string | null;
                /**
                 * Optional badge text (e.g., "Most Popular")
                 */
                badge?: string | null;
                /**
                 * Badge color (hex code)
                 */
                badgeColor?: string | null;
                /**
                 * Price display (e.g., "$499/month")
                 */
                price?: string | null;
                /**
                 * Commission info
                 */
                commission?: string | null;
                features?:
                  | {
                      feature?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                buttonText?: string | null;
                buttonVariant?: ('default' | 'outline' | 'ghost') | null;
                id?: string | null;
              }[]
            | null;
        };
        backgroundVideo?: {
          /**
           * Background video
           */
          video?: (number | null) | Media;
          /**
           * Section title
           */
          title?: string | null;
          /**
           * Section description
           */
          description?: string | null;
          minHeight?: ('50vh' | '70vh' | '100vh') | null;
        };
        specifications?: {
          /**
           * Product name for specs section
           */
          productName?: string | null;
          /**
           * Section subtitle
           */
          subtitle?: string | null;
          /**
           * Robot image for specs section
           */
          robotImage?: (number | null) | Media;
          specGroups?:
            | {
                /**
                 * Group name (e.g., "Performance", "Dimensions")
                 */
                groupName?: string | null;
                specs?:
                  | {
                      /**
                       * Spec label (e.g., "Max Speed")
                       */
                      label?: string | null;
                      /**
                       * Spec value (e.g., "20 km/h")
                       */
                      value?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
        };
        footerCTA?: {
          /**
           * Main title
           */
          title?: string | null;
          /**
           * Description text
           */
          description?: string | null;
          /**
           * Subtitle text
           */
          subtitle?: string | null;
          /**
           * CTA button text
           */
          ctaText?: string | null;
          /**
           * Robot image for footer
           */
          robotImage?: (number | null) | Media;
        };
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * SEO title (recommended: 50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * SEO description (recommended: 150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'home-page';
        value: number | HomePage;
      } | null)
    | ({
        relationTo: 'about-page';
        value: number | AboutPage;
      } | null)
    | ({
        relationTo: 'products-page';
        value: number | ProductsPage;
      } | null)
    | ({
        relationTo: 'careers-page';
        value: number | CareersPage;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'contact-page';
        value: number | ContactPage;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'dashboard-home-page';
        value: number | DashboardHomePage;
      } | null)
    | ({
        relationTo: 'product-details';
        value: number | ProductDetail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  cloudinaryFolder?: T;
  transformationPreset?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  heroSlides?:
    | T
    | {
        type?: T;
        title?: T;
        subtitle?: T;
        cursiveText?: T;
        image?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  videoSection?:
    | T
    | {
        enabled?: T;
        videoUrl?: T;
        posterImage?: T;
      };
  aboutSection?:
    | T
    | {
        foundation?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              ctaText?: T;
              ctaLink?: T;
            };
        purpose?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
            };
        vision?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
            };
        mission?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
            };
      };
  products?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        reverse?: T;
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  customSolutions?:
    | T
    | {
        id?: T;
        category?: T;
        title?: T;
        description?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
            };
      };
  metricsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        animatedStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
        staticStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        locale?: T;
        order?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        bannerImage?: T;
      };
  foundedSection?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  peopleBannerSection?:
    | T
    | {
        title?: T;
        description?: T;
        bannerImage?: T;
      };
  visionSection?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  leadershipSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        teamMembers?:
          | T
          | {
              name?: T;
              role?: T;
              imageUrl?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        bannerImage?: T;
        buttons?:
          | T
          | {
              text?: T;
              link?: T;
              variant?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        bannerImage?: T;
      };
  products?:
    | T
    | {
        id?: T;
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        reverse?: T;
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              icon?: T;
              id?: T;
            };
      };
  customSolutions?:
    | T
    | {
        id?: T;
        category?: T;
        title?: T;
        description?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        text?: T;
        link?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        locale?: T;
        order?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  title?: T;
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  introSection?:
    | T
    | {
        description?: T;
      };
  departmentsSection?:
    | T
    | {
        departments?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        ctaButtonText?: T;
      };
  missionSection?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  facilitiesSection?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  benefitsSection?:
    | T
    | {
        title?: T;
        description?: T;
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
        image?: T;
      };
  innovationSection?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  growthSection?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  peopleImageSection?:
    | T
    | {
        image?: T;
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
      };
  jobs?:
    | T
    | {
        title?: T;
        location?: T;
        date?: T;
        type?: T;
        salary?: T;
        skills?:
          | T
          | {
              skill?: T;
              id?: T;
            };
        description?: T;
        responsibilities?:
          | T
          | {
              responsibility?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              requirement?: T;
              id?: T;
            };
        qualifications?:
          | T
          | {
              qualification?: T;
              id?: T;
            };
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
        techStack?:
          | T
          | {
              tech?: T;
              id?: T;
            };
        imageKey?: T;
        applyBefore?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  featuredImage?: T;
  publishedDate?: T;
  readTime?: T;
  featured?: T;
  content?: T;
  views?: T;
  likes?: T;
  author?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  heroSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  socialMedia?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        instagram?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        officeAddress?:
          | T
          | {
              en?: T;
              ja?: T;
            };
      };
  mapLocation?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        label?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  layout?: T;
  order?: T;
  locale?: T;
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-home-page_select".
 */
export interface DashboardHomePageSelect<T extends boolean = true> {
  title?: T;
  heroSection?:
    | T
    | {
        badgeText?: T;
        title?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
        footerText?: T;
      };
  dashboardSection?:
    | T
    | {
        image?: T;
      };
  productsSection?:
    | T
    | {
        title?: T;
        description?: T;
        products?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-details_select".
 */
export interface ProductDetailsSelect<T extends boolean = true> {
  productName?: T;
  slug?: T;
  sections?:
    | T
    | {
        sectionType?: T;
        hero?:
          | T
          | {
              backgroundVideo?: T;
              title?: T;
              tagline?: T;
              primaryCTA?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
        videoWithText?:
          | T
          | {
              video?: T;
              poster?: T;
              title?: T;
              description?: T;
              titlePosition?: T;
              height?: T;
              overlayText?: T;
              overlayPosition?: T;
            };
        largeFeatureCarousel?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        cardCarousel?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cardsPerView?: T;
              navigationPosition?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        robotComparison?:
          | T
          | {
              robotImage?: T;
              specs?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
        robotTopViewGrid?:
          | T
          | {
              robotImage?: T;
              title?: T;
              subtitle?: T;
              gridCols?: T;
              gridItems?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              rightContentType?: T;
              rightContentText?: T;
              rightContentButtonText?: T;
            };
        videoWithStats?:
          | T
          | {
              video?: T;
              poster?: T;
              title?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
            };
        benefitGrid?:
          | T
          | {
              title?: T;
              sections?:
                | T
                | {
                    heading?: T;
                    subheading?: T;
                    items?:
                      | T
                      | {
                          image?: T;
                          title?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        pricing?:
          | T
          | {
              title?: T;
              description?: T;
              robotImage?: T;
              robotImageHeight?: T;
              pricingTiers?:
                | T
                | {
                    name?: T;
                    badge?: T;
                    badgeColor?: T;
                    price?: T;
                    commission?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    buttonText?: T;
                    buttonVariant?: T;
                    id?: T;
                  };
            };
        backgroundVideo?:
          | T
          | {
              video?: T;
              title?: T;
              description?: T;
              minHeight?: T;
            };
        specifications?:
          | T
          | {
              productName?: T;
              subtitle?: T;
              robotImage?: T;
              specGroups?:
                | T
                | {
                    groupName?: T;
                    specs?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        footerCTA?:
          | T
          | {
              title?: T;
              description?: T;
              subtitle?: T;
              ctaText?: T;
              robotImage?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}