/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-page': HomePage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage the home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  title: string;
  locale: 'en' | 'ja';
  heroSlides?:
    | {
        type: 'zibot' | 'glide' | 'consultancy' | 'custom';
        title?: string | null;
        subtitle?: string | null;
        cursiveText?: string | null;
        image: string;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  videoSection: {
    enabled?: boolean | null;
    videoUrl: string;
    /**
     * Optional poster image for video
     */
    posterImage?: string | null;
  };
  aboutSection: {
    foundation: {
      label?: string | null;
      title: string;
      description: string;
      ctaText?: string | null;
      ctaLink?: string | null;
    };
    purpose: {
      label?: string | null;
      title: string;
      description: string;
      image: string;
    };
    vision: {
      label?: string | null;
      title: string;
      description: string;
      image: string;
    };
    mission: {
      label?: string | null;
      title: string;
      description: string;
      image: string;
      highlights?:
        | {
            title: string;
            subtitle: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  products?:
    | {
        title: string;
        description: string;
        image: string;
        link: string;
        /**
         * Reverse layout (image on left)
         */
        reverse?: boolean | null;
        features?:
          | {
              title: string;
              subtitle: string;
              icon:
                | 'Clock'
                | 'DollarSign'
                | 'Leaf'
                | 'Shield'
                | 'Package'
                | 'CheckCircle'
                | 'UtensilsCrossed'
                | 'Hotel';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  customSolutions?:
    | {
        id: string;
        category: string;
        title: string;
        description: string;
        images?:
          | {
              src: string;
              alt: string;
              id?: string | null;
            }[]
          | null;
        features?:
          | {
              title: string;
              subtitle: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  metricsSection?: {
    title?: string | null;
    subtitle?: string | null;
    animatedStats?:
      | {
          value: number;
          label: string;
          icon: 'Package' | 'UtensilsCrossed' | 'Hotel' | 'MapPin' | 'Globe2' | 'CheckCircle';
          id?: string | null;
        }[]
      | null;
    staticStats?:
      | {
          value: string;
          label: string;
          icon: 'MapPin' | 'Globe2' | 'CheckCircle';
          id?: string | null;
        }[]
      | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        locale: 'en' | 'ja';
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'home-page';
        value: number | HomePage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  heroSlides?:
    | T
    | {
        type?: T;
        title?: T;
        subtitle?: T;
        cursiveText?: T;
        image?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  videoSection?:
    | T
    | {
        enabled?: T;
        videoUrl?: T;
        posterImage?: T;
      };
  aboutSection?:
    | T
    | {
        foundation?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              ctaText?: T;
              ctaLink?: T;
            };
        purpose?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
            };
        vision?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
            };
        mission?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
            };
      };
  products?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        reverse?: T;
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  customSolutions?:
    | T
    | {
        id?: T;
        category?: T;
        title?: T;
        description?: T;
        images?:
          | T
          | {
              src?: T;
              alt?: T;
              id?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
            };
      };
  metricsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        animatedStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
        staticStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        locale?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}